const clues = [
{
    id: 1,
    clue: 'Find the stone and solve the anagram (and put the stone back)',
    image: 'assets/1.jpeg',
    answers: ['mr biscuits', 'mr. biscuits', 'mr.biscuits', 'mrbiscuits'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 2,
    clue: 'What\'s missing from this image?',
    image: 'assets/2.jpeg',
    answers: ['3bar'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 3,
    clue: 'Find and solve the puzzle in the sand',
    image: 'assets/3.jpeg',
    answers: ['crab'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 4,
    clue: 'Find the stone and solve the anagram (and put the stone back)',
    image: 'assets/4.jpeg',
    answers: ['salum beach', 'salumbeach'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 5,
    clue: 'What\'s missing from this image?',
    image: 'assets/5.jpeg',
    answers: ['unique'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 6,
    clue: 'What colour is this flower?',
    image: 'assets/6.jpeg',
    answers: ['orange', 'vermillion', 'red-orange', 'orangey red', 'reddish orange'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 7,
    clue: 'How many rectangles are made by the gaps between the all of the tiles?',
    image: 'assets/7.jpeg',
    answers: ['58'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 8,
    clue: 'What colour is this flower?',
    image: 'assets/8.jpeg',
    answers: ['purple'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 9,
    clue: 'What\'s missing from this image?',
    image: 'assets/9.jpeg',
    answers: ['atlas'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 10,
    clue: '',
    image: 'assets/10.jpeg',
    answers: ['bottom milk'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 11,
    clue: 'Which of these spots can you see the golfballs from?',
    image: 'assets/11.jpeg',
    answers: ['a and d', 'a, d', 'a,d', 'ad'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 12,
    clue: 'How many metal bars make up the cattle grid at the front of the house?',
    image: 'assets/12.jpeg',
    answers: ['51'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 13,
    clue: 'Find the stone and solve the anagram (and put the stone back)',
    image: 'assets/13.jpeg',
    answers: ['lobster'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 14,
    clue: 'Find the stone and solve the anagram (and put the stone back)',
    image: 'assets/14.jpeg',
    answers: ['treasure hunt', 'treasurehunt'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
{
    id: 15,
    clue: 'Find the stone and solve the anagram (and put the stone back)',
    image: 'assets/15.jpeg',
    answers: ['gavin stewart', 'gavinstewart'],
    hintTask: '',
    hint: 'Ask Luke or Anna for a hint',
    state: 'locked',
},
];
