const clues = [
{
    id: 1,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 2,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 3,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 4,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 5,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 6,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 7,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 8,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 9,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 10,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 11,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 12,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 13,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 14,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
{
    id: 15,
    clue: 'clue',
    image: 'assets/placeholder.png',
    answers: ['answer'],
    hintTask: 'Complete the organiser task.',
    hint: 'hint',
    state: 'locked',
},
];